name: clang-format Check

on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Run clang-format Style Check
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '13'
        check-path: 'src'
