name: Tests

on:
  pull_request:
    branches: [ main ]
    
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tests
      - run: cmake ../src
      - run: make
